[2024-06-16T20:45:34.362+0200] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-16T20:45:34.371+0200] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: datalake_dag.index_data_to_elasticsearch manual__2024-06-16T18:45:06.938380+00:00 [queued]>
[2024-06-16T20:45:34.374+0200] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: datalake_dag.index_data_to_elasticsearch manual__2024-06-16T18:45:06.938380+00:00 [queued]>
[2024-06-16T20:45:34.374+0200] {taskinstance.py:2303} INFO - Starting attempt 1 of 1
[2024-06-16T20:45:34.390+0200] {taskinstance.py:2327} INFO - Executing <Task(PythonOperator): index_data_to_elasticsearch> on 2024-06-16 18:45:06.938380+00:00
[2024-06-16T20:45:34.392+0200] {standard_task_runner.py:63} INFO - Started process 81960 to run task
[2024-06-16T20:45:34.393+0200] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'datalake_dag', 'index_data_to_elasticsearch', 'manual__2024-06-16T18:45:06.938380+00:00', '--job-id', '226', '--raw', '--subdir', 'DAGS_FOLDER/datalake_dag.py', '--cfg-path', '/tmp/tmp696loect']
[2024-06-16T20:45:34.394+0200] {standard_task_runner.py:91} INFO - Job 226: Subtask index_data_to_elasticsearch
[2024-06-16T20:45:34.419+0200] {task_command.py:426} INFO - Running <TaskInstance: datalake_dag.index_data_to_elasticsearch manual__2024-06-16T18:45:06.938380+00:00 [running]> on host Desktop-Hector.
[2024-06-16T20:45:34.537+0200] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='datalake_dag' AIRFLOW_CTX_TASK_ID='index_data_to_elasticsearch' AIRFLOW_CTX_EXECUTION_DATE='2024-06-16T18:45:06.938380+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-06-16T18:45:06.938380+00:00'
[2024-06-16T20:45:34.537+0200] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-16T20:45:37.991+0200] {logging_mixin.py:188} INFO - Reading Parquet file from: /home/hectorv/airflow/data/usage/usage_data.parquet
[2024-06-16T20:45:39.444+0200] {logging_mixin.py:188} INFO - root
 |-- production_type: string (nullable = true)
 |-- date: string (nullable = true)
 |-- value: long (nullable = true)
 |-- carbon_emission: double (nullable = true)
 |-- emissions_total: double (nullable = true)
[2024-06-16T20:45:39.889+0200] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-16T20:45:39.890+0200] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/hectorv/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/hectorv/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/hectorv/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
  File "/home/hectorv/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
  File "/home/hectorv/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/hectorv/airflow/dags/lib/index.py", line 42, in index_data_to_elasticsearch
    df.show(5)
  File "/home/hectorv/.local/lib/python3.10/site-packages/pyspark/sql/dataframe.py", line 945, in show
    print(self._show_string(n, truncate, vertical))
  File "/home/hectorv/.local/lib/python3.10/site-packages/pyspark/sql/dataframe.py", line 963, in _show_string
    return self._jdf.showString(n, 20, vertical)
  File "/home/hectorv/.local/lib/python3.10/site-packages/py4j/java_gateway.py", line 1322, in __call__
    return_value = get_return_value(
  File "/home/hectorv/.local/lib/python3.10/site-packages/pyspark/errors/exceptions/captured.py", line 185, in deco
    raise converted from None
pyspark.errors.exceptions.captured.SparkUpgradeException: [INCONSISTENT_BEHAVIOR_CROSS_VERSION.DATETIME_PATTERN_RECOGNITION] You may get a different result due to the upgrading to Spark >= 3.0:
Fail to recognize 'MMM D, YYYY @ HH:mm:ss.SSS' pattern in the DateTimeFormatter. 1) You can set "spark.sql.legacy.timeParserPolicy" to "LEGACY" to restore the behavior before Spark 3.0. 2) You can form a valid datetime pattern with the guide from 'https://spark.apache.org/docs/latest/sql-ref-datetime-pattern.html'.
[2024-06-16T20:45:39.900+0200] {taskinstance.py:1205} INFO - Marking task as FAILED. dag_id=datalake_dag, task_id=index_data_to_elasticsearch, execution_date=20240616T184506, start_date=20240616T184534, end_date=20240616T184539
[2024-06-16T20:45:39.916+0200] {standard_task_runner.py:110} ERROR - Failed to execute job 226 for task index_data_to_elasticsearch ([INCONSISTENT_BEHAVIOR_CROSS_VERSION.DATETIME_PATTERN_RECOGNITION] You may get a different result due to the upgrading to Spark >= 3.0:
Fail to recognize 'MMM D, YYYY @ HH:mm:ss.SSS' pattern in the DateTimeFormatter. 1) You can set "spark.sql.legacy.timeParserPolicy" to "LEGACY" to restore the behavior before Spark 3.0. 2) You can form a valid datetime pattern with the guide from 'https://spark.apache.org/docs/latest/sql-ref-datetime-pattern.html'.; 81960)
[2024-06-16T20:45:39.932+0200] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-06-16T20:45:40.008+0200] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-16T20:45:40.009+0200] {local_task_job_runner.py:222} INFO - ::endgroup::
