[2024-06-16T10:33:51.748+0200] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-16T10:33:51.758+0200] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: datalake_dag.format_consumption_data manual__2024-06-16T08:33:23.045400+00:00 [queued]>
[2024-06-16T10:33:51.760+0200] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: datalake_dag.format_consumption_data manual__2024-06-16T08:33:23.045400+00:00 [queued]>
[2024-06-16T10:33:51.760+0200] {taskinstance.py:2303} INFO - Starting attempt 1 of 1
[2024-06-16T10:33:51.842+0200] {taskinstance.py:2327} INFO - Executing <Task(PythonOperator): format_consumption_data> on 2024-06-16 08:33:23.045400+00:00
[2024-06-16T10:33:51.844+0200] {standard_task_runner.py:63} INFO - Started process 821 to run task
[2024-06-16T10:33:51.844+0200] {clientserver.py:543} INFO - Closing down clientserver connection
[2024-06-16T10:33:51.846+0200] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'datalake_dag', 'format_consumption_data', 'manual__2024-06-16T08:33:23.045400+00:00', '--job-id', '154', '--raw', '--subdir', 'DAGS_FOLDER/datalake_dag.py', '--cfg-path', '/tmp/tmpcs697lr8']
[2024-06-16T10:33:51.846+0200] {standard_task_runner.py:91} INFO - Job 154: Subtask format_consumption_data
[2024-06-16T10:33:51.872+0200] {task_command.py:426} INFO - Running <TaskInstance: datalake_dag.format_consumption_data manual__2024-06-16T08:33:23.045400+00:00 [running]> on host Desktop-Hector.
[2024-06-16T10:33:51.916+0200] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='datalake_dag' AIRFLOW_CTX_TASK_ID='format_consumption_data' AIRFLOW_CTX_EXECUTION_DATE='2024-06-16T08:33:23.045400+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-06-16T08:33:23.045400+00:00'
[2024-06-16T10:33:51.917+0200] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-16T10:33:51.924+0200] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-16T10:33:51.924+0200] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/hectorv/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/hectorv/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/hectorv/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
  File "/home/hectorv/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
  File "/home/hectorv/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/hectorv/airflow/dags/lib/format_digital_iservices_data.py", line 36, in format_consumption_data
    sc = SparkContext('local')
  File "/home/hectorv/.local/lib/python3.10/site-packages/pyspark/context.py", line 201, in __init__
    SparkContext._ensure_initialized(self, gateway=gateway, conf=conf)
  File "/home/hectorv/.local/lib/python3.10/site-packages/pyspark/context.py", line 449, in _ensure_initialized
    raise ValueError(
ValueError: Cannot run multiple SparkContexts at once; existing SparkContext(app=pyspark-shell, master=local) created by __init__ at /home/hectorv/airflow/dags/lib/format_digital_iservices_data.py:36 
[2024-06-16T10:33:51.926+0200] {taskinstance.py:1205} INFO - Marking task as FAILED. dag_id=datalake_dag, task_id=format_consumption_data, execution_date=20240616T083323, start_date=20240616T083351, end_date=20240616T083351
[2024-06-16T10:33:51.941+0200] {standard_task_runner.py:110} ERROR - Failed to execute job 154 for task format_consumption_data (Cannot run multiple SparkContexts at once; existing SparkContext(app=pyspark-shell, master=local) created by __init__ at /home/hectorv/airflow/dags/lib/format_digital_iservices_data.py:36 ; 821)
[2024-06-16T10:33:51.977+0200] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-06-16T10:33:51.985+0200] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-16T10:33:51.985+0200] {local_task_job_runner.py:222} INFO - ::endgroup::
